[green_agent]
# actions
image = "ghcr.io/rdi-foundation/tau2-agentbeats:latest"
name = "green"
env = { LOG_LEVEL = "INFO", OPENAI_API_KEY = "${LLM_API_KEY}", OPENAI_BASE_URL = "https://routerai.ru/api/v1", GEMINI_API_KEY = "none", DEEPSEEK_API_KEY = "none" }

[[participants]]
image = "ghcr.io/ddreamboy/tau2-purple-agent:latest"
name = "agent"
env = { LOG_LEVEL = "INFO", LLM_API_KEY = "${LLM_API_KEY}", LLM_API_URL = "https://routerai.ru/api/v1", LLM_API_BASE_MODEL = "google/gemini-2.5-flash-lite" }

[config]
domain = "airline"
user_llm = "openai/google/gemini-2.5-flash-lite"
